/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as CollectionRouteImport } from './routes/collection'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MembershipRouteImport } from './routes/membership'
import { Route as OwnersRouteImport } from './routes/owners'
import { Route as PhotographyRouteImport } from './routes/photography'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SafetyRouteImport } from './routes/safety'
import { Route as SellRouteImport } from './routes/sell'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as TouringRouteImport } from './routes/touring'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as AdminCollectionRouteImport } from './routes/admin.collection'
import { Route as AdminInquiriesRouteImport } from './routes/admin.inquiries'
import { Route as AdminIntakeRouteImport } from './routes/admin.intake'
import { Route as AdminMembersRouteImport } from './routes/admin.members'
import { Route as AdminOwnersRouteImport } from './routes/admin.owners'
import { Route as ApplyCollectionRouteImport } from './routes/apply/collection'
import { Route as ApplyMemberRouteImport } from './routes/apply/member'
import { Route as ApplyOwnerRouteImport } from './routes/apply/owner'
import { Route as LoginResetRouteImport } from './routes/login_.reset'
import { Route as AdminCollectionIdRouteImport } from './routes/admin.collection.$id'
import { Route as AdminInquiriesIdRouteImport } from './routes/admin.inquiries.$id'
import { Route as AdminMembersIdRouteImport } from './routes/admin.members.$id'
import { Route as AdminOwnersIdRouteImport } from './routes/admin.owners.$id'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const CollectionRoute = CollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MembershipRoute = MembershipRouteImport.update({
  id: '/membership',
  path: '/membership',
  getParentRoute: () => rootRouteImport,
} as any)
const OwnersRoute = OwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => rootRouteImport,
} as any)
const PhotographyRoute = PhotographyRouteImport.update({
  id: '/photography',
  path: '/photography',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SafetyRoute = SafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => rootRouteImport,
} as any)
const SellRoute = SellRouteImport.update({
  id: '/sell',
  path: '/sell',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const TouringRoute = TouringRouteImport.update({
  id: '/touring',
  path: '/touring',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCollectionRoute = AdminCollectionRouteImport.update({
  id: '/collection',
  path: '/collection',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInquiriesRoute = AdminInquiriesRouteImport.update({
  id: '/inquiries',
  path: '/inquiries',
  getParentRoute: () => AdminRoute,
} as any)
const AdminIntakeRoute = AdminIntakeRouteImport.update({
  id: '/intake',
  path: '/intake',
  getParentRoute: () => AdminRoute,
} as any)
const AdminMembersRoute = AdminMembersRouteImport.update({
  id: '/members',
  path: '/members',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOwnersRoute = AdminOwnersRouteImport.update({
  id: '/owners',
  path: '/owners',
  getParentRoute: () => AdminRoute,
} as any)
const ApplyCollectionRoute = ApplyCollectionRouteImport.update({
  id: '/apply/collection',
  path: '/apply/collection',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyMemberRoute = ApplyMemberRouteImport.update({
  id: '/apply/member',
  path: '/apply/member',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyOwnerRoute = ApplyOwnerRouteImport.update({
  id: '/apply/owner',
  path: '/apply/owner',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginResetRoute = LoginResetRouteImport.update({
  id: '/login_/reset',
  path: '/login/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCollectionIdRoute = AdminCollectionIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminCollectionRoute,
} as any)
const AdminInquiriesIdRoute = AdminInquiriesIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminInquiriesRoute,
} as any)
const AdminMembersIdRoute = AdminMembersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminMembersRoute,
} as any)
const AdminOwnersIdRoute = AdminOwnersIdRouteImport.update({
  id: '/$id',
  path: '/$id',
  getParentRoute: () => AdminOwnersRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/owners': typeof OwnersRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/touring': typeof TouringRoute
  '/admin/collection': typeof AdminCollectionRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/owners': typeof AdminOwnersRouteWithChildren
  '/apply/collection': typeof ApplyCollectionRoute
  '/apply/member': typeof ApplyMemberRoute
  '/apply/owner': typeof ApplyOwnerRoute
  '/login/reset': typeof LoginResetRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collection/$id': typeof AdminCollectionIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/owners/$id': typeof AdminOwnersIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/owners': typeof OwnersRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/touring': typeof TouringRoute
  '/admin/collection': typeof AdminCollectionRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/owners': typeof AdminOwnersRouteWithChildren
  '/apply/collection': typeof ApplyCollectionRoute
  '/apply/member': typeof ApplyMemberRoute
  '/apply/owner': typeof ApplyOwnerRoute
  '/login/reset': typeof LoginResetRoute
  '/admin': typeof AdminIndexRoute
  '/admin/collection/$id': typeof AdminCollectionIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/owners/$id': typeof AdminOwnersIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/collection': typeof CollectionRoute
  '/contact': typeof ContactRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/login': typeof LoginRoute
  '/membership': typeof MembershipRoute
  '/owners': typeof OwnersRoute
  '/photography': typeof PhotographyRoute
  '/privacy': typeof PrivacyRoute
  '/safety': typeof SafetyRoute
  '/sell': typeof SellRoute
  '/terms': typeof TermsRoute
  '/touring': typeof TouringRoute
  '/admin/collection': typeof AdminCollectionRouteWithChildren
  '/admin/inquiries': typeof AdminInquiriesRouteWithChildren
  '/admin/intake': typeof AdminIntakeRoute
  '/admin/members': typeof AdminMembersRouteWithChildren
  '/admin/owners': typeof AdminOwnersRouteWithChildren
  '/apply/collection': typeof ApplyCollectionRoute
  '/apply/member': typeof ApplyMemberRoute
  '/apply/owner': typeof ApplyOwnerRoute
  '/login_/reset': typeof LoginResetRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/collection/$id': typeof AdminCollectionIdRoute
  '/admin/inquiries/$id': typeof AdminInquiriesIdRoute
  '/admin/members/$id': typeof AdminMembersIdRoute
  '/admin/owners/$id': typeof AdminOwnersIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/membership'
    | '/owners'
    | '/photography'
    | '/privacy'
    | '/safety'
    | '/sell'
    | '/terms'
    | '/touring'
    | '/admin/collection'
    | '/admin/inquiries'
    | '/admin/intake'
    | '/admin/members'
    | '/admin/owners'
    | '/apply/collection'
    | '/apply/member'
    | '/apply/owner'
    | '/login/reset'
    | '/admin/'
    | '/admin/collection/$id'
    | '/admin/inquiries/$id'
    | '/admin/members/$id'
    | '/admin/owners/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/membership'
    | '/owners'
    | '/photography'
    | '/privacy'
    | '/safety'
    | '/sell'
    | '/terms'
    | '/touring'
    | '/admin/collection'
    | '/admin/inquiries'
    | '/admin/intake'
    | '/admin/members'
    | '/admin/owners'
    | '/apply/collection'
    | '/apply/member'
    | '/apply/owner'
    | '/login/reset'
    | '/admin'
    | '/admin/collection/$id'
    | '/admin/inquiries/$id'
    | '/admin/members/$id'
    | '/admin/owners/$id'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/collection'
    | '/contact'
    | '/faq'
    | '/how-it-works'
    | '/login'
    | '/membership'
    | '/owners'
    | '/photography'
    | '/privacy'
    | '/safety'
    | '/sell'
    | '/terms'
    | '/touring'
    | '/admin/collection'
    | '/admin/inquiries'
    | '/admin/intake'
    | '/admin/members'
    | '/admin/owners'
    | '/apply/collection'
    | '/apply/member'
    | '/apply/owner'
    | '/login_/reset'
    | '/admin/'
    | '/admin/collection/$id'
    | '/admin/inquiries/$id'
    | '/admin/members/$id'
    | '/admin/owners/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  CollectionRoute: typeof CollectionRoute
  ContactRoute: typeof ContactRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  LoginRoute: typeof LoginRoute
  MembershipRoute: typeof MembershipRoute
  OwnersRoute: typeof OwnersRoute
  PhotographyRoute: typeof PhotographyRoute
  PrivacyRoute: typeof PrivacyRoute
  SafetyRoute: typeof SafetyRoute
  SellRoute: typeof SellRoute
  TermsRoute: typeof TermsRoute
  TouringRoute: typeof TouringRoute
  ApplyCollectionRoute: typeof ApplyCollectionRoute
  ApplyMemberRoute: typeof ApplyMemberRoute
  ApplyOwnerRoute: typeof ApplyOwnerRoute
  LoginResetRoute: typeof LoginResetRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/collection': {
      id: '/collection'
      path: '/collection'
      fullPath: '/collection'
      preLoaderRoute: typeof CollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/membership': {
      id: '/membership'
      path: '/membership'
      fullPath: '/membership'
      preLoaderRoute: typeof MembershipRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/owners': {
      id: '/owners'
      path: '/owners'
      fullPath: '/owners'
      preLoaderRoute: typeof OwnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/photography': {
      id: '/photography'
      path: '/photography'
      fullPath: '/photography'
      preLoaderRoute: typeof PhotographyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safety': {
      id: '/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof SafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sell': {
      id: '/sell'
      path: '/sell'
      fullPath: '/sell'
      preLoaderRoute: typeof SellRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/touring': {
      id: '/touring'
      path: '/touring'
      fullPath: '/touring'
      preLoaderRoute: typeof TouringRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/collection': {
      id: '/admin/collection'
      path: '/collection'
      fullPath: '/admin/collection'
      preLoaderRoute: typeof AdminCollectionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/inquiries': {
      id: '/admin/inquiries'
      path: '/inquiries'
      fullPath: '/admin/inquiries'
      preLoaderRoute: typeof AdminInquiriesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/intake': {
      id: '/admin/intake'
      path: '/intake'
      fullPath: '/admin/intake'
      preLoaderRoute: typeof AdminIntakeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/members': {
      id: '/admin/members'
      path: '/members'
      fullPath: '/admin/members'
      preLoaderRoute: typeof AdminMembersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/owners': {
      id: '/admin/owners'
      path: '/owners'
      fullPath: '/admin/owners'
      preLoaderRoute: typeof AdminOwnersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/apply/collection': {
      id: '/apply/collection'
      path: '/apply/collection'
      fullPath: '/apply/collection'
      preLoaderRoute: typeof ApplyCollectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/member': {
      id: '/apply/member'
      path: '/apply/member'
      fullPath: '/apply/member'
      preLoaderRoute: typeof ApplyMemberRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply/owner': {
      id: '/apply/owner'
      path: '/apply/owner'
      fullPath: '/apply/owner'
      preLoaderRoute: typeof ApplyOwnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login_/reset': {
      id: '/login_/reset'
      path: '/login/reset'
      fullPath: '/login/reset'
      preLoaderRoute: typeof LoginResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/collection/$id': {
      id: '/admin/collection/$id'
      path: '/$id'
      fullPath: '/admin/collection/$id'
      preLoaderRoute: typeof AdminCollectionIdRouteImport
      parentRoute: typeof AdminCollectionRoute
    }
    '/admin/inquiries/$id': {
      id: '/admin/inquiries/$id'
      path: '/$id'
      fullPath: '/admin/inquiries/$id'
      preLoaderRoute: typeof AdminInquiriesIdRouteImport
      parentRoute: typeof AdminInquiriesRoute
    }
    '/admin/members/$id': {
      id: '/admin/members/$id'
      path: '/$id'
      fullPath: '/admin/members/$id'
      preLoaderRoute: typeof AdminMembersIdRouteImport
      parentRoute: typeof AdminMembersRoute
    }
    '/admin/owners/$id': {
      id: '/admin/owners/$id'
      path: '/$id'
      fullPath: '/admin/owners/$id'
      preLoaderRoute: typeof AdminOwnersIdRouteImport
      parentRoute: typeof AdminOwnersRoute
    }
  }
}

interface AdminCollectionRouteChildren {
  AdminCollectionIdRoute: typeof AdminCollectionIdRoute
}

const AdminCollectionRouteChildren: AdminCollectionRouteChildren = {
  AdminCollectionIdRoute: AdminCollectionIdRoute,
}

const AdminCollectionRouteWithChildren = AdminCollectionRoute._addFileChildren(
  AdminCollectionRouteChildren,
)

interface AdminInquiriesRouteChildren {
  AdminInquiriesIdRoute: typeof AdminInquiriesIdRoute
}

const AdminInquiriesRouteChildren: AdminInquiriesRouteChildren = {
  AdminInquiriesIdRoute: AdminInquiriesIdRoute,
}

const AdminInquiriesRouteWithChildren = AdminInquiriesRoute._addFileChildren(
  AdminInquiriesRouteChildren,
)

interface AdminMembersRouteChildren {
  AdminMembersIdRoute: typeof AdminMembersIdRoute
}

const AdminMembersRouteChildren: AdminMembersRouteChildren = {
  AdminMembersIdRoute: AdminMembersIdRoute,
}

const AdminMembersRouteWithChildren = AdminMembersRoute._addFileChildren(
  AdminMembersRouteChildren,
)

interface AdminOwnersRouteChildren {
  AdminOwnersIdRoute: typeof AdminOwnersIdRoute
}

const AdminOwnersRouteChildren: AdminOwnersRouteChildren = {
  AdminOwnersIdRoute: AdminOwnersIdRoute,
}

const AdminOwnersRouteWithChildren = AdminOwnersRoute._addFileChildren(
  AdminOwnersRouteChildren,
)

interface AdminRouteChildren {
  AdminCollectionRoute: typeof AdminCollectionRouteWithChildren
  AdminInquiriesRoute: typeof AdminInquiriesRouteWithChildren
  AdminIntakeRoute: typeof AdminIntakeRoute
  AdminMembersRoute: typeof AdminMembersRouteWithChildren
  AdminOwnersRoute: typeof AdminOwnersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCollectionRoute: AdminCollectionRouteWithChildren,
  AdminInquiriesRoute: AdminInquiriesRouteWithChildren,
  AdminIntakeRoute: AdminIntakeRoute,
  AdminMembersRoute: AdminMembersRouteWithChildren,
  AdminOwnersRoute: AdminOwnersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  CollectionRoute: CollectionRoute,
  ContactRoute: ContactRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  LoginRoute: LoginRoute,
  MembershipRoute: MembershipRoute,
  OwnersRoute: OwnersRoute,
  PhotographyRoute: PhotographyRoute,
  PrivacyRoute: PrivacyRoute,
  SafetyRoute: SafetyRoute,
  SellRoute: SellRoute,
  TermsRoute: TermsRoute,
  TouringRoute: TouringRoute,
  ApplyCollectionRoute: ApplyCollectionRoute,
  ApplyMemberRoute: ApplyMemberRoute,
  ApplyOwnerRoute: ApplyOwnerRoute,
  LoginResetRoute: LoginResetRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
